title: Shabbos Project Chicago Northshore
email: support@phaxio.com
url: "http://northshore.shabbatprojectchicago.org"
markdown: kramdown
permalink: blog/:year/:month/:day/:title.html
exclude: [Gemfile, Gemfile.lock]

sass:
    style: compressed

defaults:
  -
   scope:
     path: ""
   values:
     layout: "default"